- name: Install sgoinfre requirements
  pacman:
    name:
      - nfs-utils

- name: Install the sgoinfre mount file
  template:
    src: systemd/sgoinfre.mount
    dest: /etc/systemd/system
  notify: restart sgoinfre mount

- name: Enable the sgoinfre mount
  systemd:
    name: sgoinfre.mount
    enabled: true
  notify: restart sgoinfre mount
