all:
  hosts:
    gw:
      ansible_host: mygw
    web:
      ansible_host: myweb
    misc:
      ansible_host: myweb
    monitoring:
      ansible_host: myweb
    rhfs01:
      ansible_host: myrhfs01

  vars:
    ansible_python_interpreter: python3

    container_setup: true

    dhcp_ignore_subnets:
      - subnet: 10.0.0.0
        netmask: 255.255.255.0
      - subnet: 169.254.0.0
        netmask: 255.255.0.0

    contest_enabled: true
    contest_end: "2042-42-42 20:00:00"

    concours_db_name: concours2019
    concours_game: prologin2019
    concours_use_maps: true
    concours_static_path: /var/prologin/prologin2019/www/static
    concours_map_validator_script: /var/prologin/prologin2019/www/validator.py
    concours_enable_replay: true

    hfs_db_password: 5cf70e56a13c95c2fe40ae38276f469a
    hfs_secret: c39bf626f65dc6769657577bd46ef1e6
    mdb_db_password: c7d1d0be60bfafcdd2d4fbe38eedb8f3
    mdb_secret_key: e20f7bef693662908d68f17c4d25eee3
    mdbsync_secret: 558dca37345477fdca71422e0b0e46a6
    presenced_secret: 5154fe67e519b2efce5d08d26623da38
    presencesync_secret: 8c1f8ee2db32bb0bcce8a60bf424b30f
    udb_db_password: a4d222ae0d0cf8bdebfb789807db1ee5
    udb_secret_key: 8ef6be1682a7d193e6fcac4165383823
    udbauth_secret: 63bfb773c1c88d4d4ba3f55a74fbe4d3
    udbsync_secret: 360ffe37559d4f3128e82b1381625651

    concours_db_password: dcf9ccfeb05b3e1da397d3a50c4eb4f7
    concours_secret: 718152674713fda2bef5c89bdf4a54be
    homepage_db_password: 03667d7223b1056d95fe722beef3f6e9
    homepage_secret: 280687f71bc24c07cf08e401bf429b42
    masternode_secret: 67f6f3ac095d28ac4f0c2f1a61e7b722
    redmine_db_password: 7fbf1f3c9e3c97a4db5c5f9ed51dd6ca
