all:
  hosts:
    gw:
      ansible_host: mygw
    web:
      ansible_host: myweb
    misc:
      ansible_host: myweb
    monitoring:
      ansible_host: myweb
    rhfs01:
      ansible_host: myrhfs01

  vars:
    ansible_python_interpreter: python3
