- name: Create the PostgreSQL HFSDB user
  postgresql_user:
    name: hfs
    password: '{{ hfs_db_password }}'
    encrypted: yes
  no_log: true
  become: true
  become_user: postgres

- name: Create the PostgreSQL HFSDB database
  postgresql_db:
    name: '{{ item }}'
    owner: hfs
  loop:
    - hfs
    - hfscontest
  become: true
  become_user: postgres

- name: Create the HFSDB user_location table
  postgresql_table:
    db: '{{ item }}'
    owner: hfs
    name: user_location
    columns:
      - id SERIAL
      - hfs INTEGER
      - username VARCHAR
  loop:
    - hfs
    - hfscontest
  become: true
  become_user: postgres
