- name: Install Bind
  pacman:
    name: bind

- name: Install named config
  template:
    src: 'named.conf'
    dest: '/etc/named.conf'
    lstrip_blocks: yes
    owner: root
    group: named
    mode: 0640
  notify: reload bind

- name: Create named directory
  file:
    path: '/etc/named'
    state: directory
    owner: named
    group: mdbdns
    mode: 0770

- name: Install named zones
  template:
    src: 'named/{{ item }}'
    dest: '/etc/named/{{ item }}'
    owner: named
    group: named
    mode: 0640
  loop:
    - '0.in-addr.arpa.zone'
    - '127.in-addr.arpa.zone'
    - '255.in-addr.arpa.zone'
    - 'localhost.zone'
    - 'root.hint'
  notify: reload bind

- name: Create named log file
  copy:
    content: ""
    dest: '/var/log/named.log'
    force: no
    owner: named
    group: root
    mode: 0640

- name: Generate RNDC key
  command: rndc-confgen -a
  args:
    creates: '/etc/rndc.key'
  notify: reload bind

- name: Set RNDC key permissions
  file:
    path: '/etc/rndc.key'
    owner: named
    group: mdbdns
    mode: 0640

- name: Enable bind
  systemd:
    name: named
    state: started
    enabled: True
