groups:
- name: sadm.rules
  rules:
  - alert: gw.prolo_postgresql.service_NotActive
    annotations:
      description: ssh gw.prolo journalctl -eu postgresql.service
      summary: postgresql.service is not active on gw.prolo
    expr: node_systemd_unit_state{instance="gw.prolo", name="postgresql.service", state="active"} == 0
    for: 30s
  - alert: gw.prolo_mdb.service_NotActive
    annotations:
      description: ssh gw.prolo journalctl -eu mdb.service
      summary: mdb.service is not active on gw.prolo
    expr: node_systemd_unit_state{instance="gw.prolo", name="mdb.service", state="active"} == 0
    for: 30s
  - alert: gw.prolo_nginx.service_NotActive
    annotations:
      description: ssh gw.prolo journalctl -eu nginx.service
      summary: nginx.service is not active on gw.prolo
    expr: node_systemd_unit_state{instance="gw.prolo", name="nginx.service", state="active"} == 0
    for: 30s
  - alert: gw.prolo_mdbsync.service_NotActive
    annotations:
      description: ssh gw.prolo journalctl -eu mdbsync.service
      summary: mdbsync.service is not active on gw.prolo
    expr: node_systemd_unit_state{instance="gw.prolo", name="mdbsync.service", state="active"} == 0
    for: 30s
  - alert: gw.prolo_mdbdns.service_NotActive
    annotations:
      description: ssh gw.prolo journalctl -eu mdbdns.service
      summary: mdbdns.service is not active on gw.prolo
    expr: node_systemd_unit_state{instance="gw.prolo", name="mdbdns.service", state="active"} == 0
    for: 30s
  - alert: gw.prolo_named.service_NotActive
    annotations:
      description: ssh gw.prolo journalctl -eu named.service
      summary: named.service is not active on gw.prolo
    expr: node_systemd_unit_state{instance="gw.prolo", name="named.service", state="active"} == 0
    for: 30s
  - alert: gw.prolo_mdbdhcp.service_NotActive
    annotations:
      description: ssh gw.prolo journalctl -eu mdbdhcp.service
      summary: mdbdhcp.service is not active on gw.prolo
    expr: node_systemd_unit_state{instance="gw.prolo", name="mdbdhcp.service", state="active"} == 0
    for: 30s
  - alert: gw.prolo_dhcpd4.service_NotActive
    annotations:
      description: ssh gw.prolo journalctl -eu dhcpd4.service
      summary: dhcpd4.service is not active on gw.prolo
    expr: node_systemd_unit_state{instance="gw.prolo", name="dhcpd4.service", state="active"} == 0
    for: 30s
  - alert: gw.prolo_netboot.service_NotActive
    annotations:
      description: ssh gw.prolo journalctl -eu netboot.service
      summary: netboot.service is not active on gw.prolo
    expr: node_systemd_unit_state{instance="gw.prolo", name="netboot.service", state="active"} == 0
    for: 30s
  - alert: gw.prolo_tftpd.socket_NotActive
    annotations:
      description: ssh gw.prolo journalctl -eu tftpd.socket
      summary: tftpd.socket is not active on gw.prolo
    expr: node_systemd_unit_state{instance="gw.prolo", name="tftpd.socket", state="active"} == 0
    for: 30s
  - alert: gw.prolo_udb.service_NotActive
    annotations:
      description: ssh gw.prolo journalctl -eu udb.service
      summary: udb.service is not active on gw.prolo
    expr: node_systemd_unit_state{instance="gw.prolo", name="udb.service", state="active"} == 0
    for: 30s
  - alert: gw.prolo_udbsync.service_NotActive
    annotations:
      description: ssh gw.prolo journalctl -eu udbsync.service
      summary: udbsync.service is not active on gw.prolo
    expr: node_systemd_unit_state{instance="gw.prolo", name="udbsync.service", state="active"} == 0
    for: 30s
  - alert: gw.prolo_udbsync_django@mdb.service_NotActive
    annotations:
      description: ssh gw.prolo journalctl -eu udbsync_django@mdb.service
      summary: udbsync_django@mdb.service is not active on gw.prolo
    expr: node_systemd_unit_state{instance="gw.prolo", name="udbsync_django@mdb.service", state="active"} == 0
    for: 30s
  - alert: gw.prolo_udbsync_django@udb.service_NotActive
    annotations:
      description: ssh gw.prolo journalctl -eu udbsync_django@udb.service
      summary: udbsync_django@udb.service is not active on gw.prolo
    expr: node_systemd_unit_state{instance="gw.prolo", name="udbsync_django@udb.service", state="active"} == 0
    for: 30s
  - alert: gw.prolo_udbsync_rootssh.service_NotActive
    annotations:
      description: ssh gw.prolo journalctl -eu udbsync_rootssh.service
      summary: udbsync_rootssh.service is not active on gw.prolo
    expr: node_systemd_unit_state{instance="gw.prolo", name="udbsync_rootssh.service", state="active"} == 0
    for: 30s
  - alert: gw.prolo_presencesync.service_NotActive
    annotations:
      description: ssh gw.prolo journalctl -eu presencesync.service
      summary: presencesync.service is not active on gw.prolo
    expr: node_systemd_unit_state{instance="gw.prolo", name="presencesync.service", state="active"} == 0
    for: 30s
  - alert: gw.prolo_presencesync_sso.service_NotActive
    annotations:
      description: ssh gw.prolo journalctl -eu presencesync_sso.service
      summary: presencesync_sso.service is not active on gw.prolo
    expr: node_systemd_unit_state{instance="gw.prolo", name="presencesync_sso.service", state="active"} == 0
    for: 30s
  - alert: gw.prolo_firewall.service_NotActive
    annotations:
      description: ssh gw.prolo journalctl -eu firewall.service
      summary: firewall.service is not active on gw.prolo
    expr: node_systemd_unit_state{instance="gw.prolo", name="firewall.service", state="active"} == 0
    for: 30s
  - alert: gw.prolo_presencesync_firewall.service_NotActive
    annotations:
      description: ssh gw.prolo journalctl -eu presencesync_firewall.service
      summary: presencesync_firewall.service is not active on gw.prolo
    expr: node_systemd_unit_state{instance="gw.prolo", name="presencesync_firewall.service", state="active"} == 0
    for: 30s
  - alert: rhfs01.prolo_udbsync_passwd.service_NotActive
    annotations:
      description: ssh rhfs01.prolo journalctl -eu udbsync_passwd.service
      summary: udbsync_passwd.service is not active on rhfs01.prolo
    expr: node_systemd_unit_state{instance="rhfs01.prolo", name="udbsync_passwd.service", state="active"} == 0
    for: 30s
  - alert: rhfs01.prolo_udbsync_passwd_nfsroot.service_NotActive
    annotations:
      description: ssh rhfs01.prolo journalctl -eu udbsync_passwd_nfsroot.service
      summary: udbsync_passwd_nfsroot.service is not active on rhfs01.prolo
    expr: node_systemd_unit_state{instance="rhfs01.prolo", name="udbsync_passwd_nfsroot.service", state="active"} == 0
    for: 30s
  - alert: rhfs01.prolo_udbsync_rootssh.service_NotActive
    annotations:
      description: ssh rhfs01.prolo journalctl -eu udbsync_rootssh.service
      summary: udbsync_rootssh.service is not active on rhfs01.prolo
    expr: node_systemd_unit_state{instance="rhfs01.prolo", name="udbsync_rootssh.service", state="active"} == 0
    for: 30s
  - alert: rhfs01.prolo_rpcbind.service_NotActive
    annotations:
      description: ssh rhfs01.prolo journalctl -eu rpcbind.service
      summary: rpcbind.service is not active on rhfs01.prolo
    expr: node_systemd_unit_state{instance="rhfs01.prolo", name="rpcbind.service", state="active"} == 0
    for: 30s
  - alert: rhfs01.prolo_nfs-server.service_NotActive
    annotations:
      description: ssh rhfs01.prolo journalctl -eu nfs-server.service
      summary: nfs-server.service is not active on rhfs01.prolo
    expr: node_systemd_unit_state{instance="rhfs01.prolo", name="nfs-server.service", state="active"} == 0
    for: 30s
  - alert: rhfs01.prolo_rootssh.path_NotActive
    annotations:
      description: ssh rhfs01.prolo journalctl -eu rootssh.path
      summary: rootssh.path is not active on rhfs01.prolo
    expr: node_systemd_unit_state{instance="rhfs01.prolo", name="rootssh.path", state="active"} == 0
    for: 30s
  - alert: rhfs23.prolo_udbsync_passwd.service_NotActive
    annotations:
      description: ssh rhfs23.prolo journalctl -eu udbsync_passwd.service
      summary: udbsync_passwd.service is not active on rhfs23.prolo
    expr: node_systemd_unit_state{instance="rhfs23.prolo", name="udbsync_passwd.service", state="active"} == 0
    for: 30s
  - alert: rhfs23.prolo_udbsync_passwd_nfsroot.service_NotActive
    annotations:
      description: ssh rhfs23.prolo journalctl -eu udbsync_passwd_nfsroot.service
      summary: udbsync_passwd_nfsroot.service is not active on rhfs23.prolo
    expr: node_systemd_unit_state{instance="rhfs23.prolo", name="udbsync_passwd_nfsroot.service", state="active"} == 0
    for: 30s
  - alert: rhfs23.prolo_udbsync_rootssh.service_NotActive
    annotations:
      description: ssh rhfs23.prolo journalctl -eu udbsync_rootssh.service
      summary: udbsync_rootssh.service is not active on rhfs23.prolo
    expr: node_systemd_unit_state{instance="rhfs23.prolo", name="udbsync_rootssh.service", state="active"} == 0
    for: 30s
  - alert: rhfs23.prolo_rpcbind.service_NotActive
    annotations:
      description: ssh rhfs23.prolo journalctl -eu rpcbind.service
      summary: rpcbind.service is not active on rhfs23.prolo
    expr: node_systemd_unit_state{instance="rhfs23.prolo", name="rpcbind.service", state="active"} == 0
    for: 30s
  - alert: rhfs23.prolo_nfs-server.service_NotActive
    annotations:
      description: ssh rhfs23.prolo journalctl -eu nfs-server.service
      summary: nfs-server.service is not active on rhfs23.prolo
    expr: node_systemd_unit_state{instance="rhfs23.prolo", name="nfs-server.service", state="active"} == 0
    for: 30s
  - alert: rhfs23.prolo_rootssh.path_NotActive
    annotations:
      description: ssh rhfs23.prolo journalctl -eu rootssh.path
      summary: rootssh.path is not active on rhfs23.prolo
    expr: node_systemd_unit_state{instance="rhfs23.prolo", name="rootssh.path", state="active"} == 0
    for: 30s
  - alert: rhfs45.prolo_udbsync_passwd.service_NotActive
    annotations:
      description: ssh rhfs45.prolo journalctl -eu udbsync_passwd.service
      summary: udbsync_passwd.service is not active on rhfs45.prolo
    expr: node_systemd_unit_state{instance="rhfs45.prolo", name="udbsync_passwd.service", state="active"} == 0
    for: 30s
  - alert: rhfs45.prolo_udbsync_passwd_nfsroot.service_NotActive
    annotations:
      description: ssh rhfs45.prolo journalctl -eu udbsync_passwd_nfsroot.service
      summary: udbsync_passwd_nfsroot.service is not active on rhfs45.prolo
    expr: node_systemd_unit_state{instance="rhfs45.prolo", name="udbsync_passwd_nfsroot.service", state="active"} == 0
    for: 30s
  - alert: rhfs45.prolo_udbsync_rootssh.service_NotActive
    annotations:
      description: ssh rhfs45.prolo journalctl -eu udbsync_rootssh.service
      summary: udbsync_rootssh.service is not active on rhfs45.prolo
    expr: node_systemd_unit_state{instance="rhfs45.prolo", name="udbsync_rootssh.service", state="active"} == 0
    for: 30s
  - alert: rhfs45.prolo_rpcbind.service_NotActive
    annotations:
      description: ssh rhfs45.prolo journalctl -eu rpcbind.service
      summary: rpcbind.service is not active on rhfs45.prolo
    expr: node_systemd_unit_state{instance="rhfs45.prolo", name="rpcbind.service", state="active"} == 0
    for: 30s
  - alert: rhfs45.prolo_nfs-server.service_NotActive
    annotations:
      description: ssh rhfs45.prolo journalctl -eu nfs-server.service
      summary: nfs-server.service is not active on rhfs45.prolo
    expr: node_systemd_unit_state{instance="rhfs45.prolo", name="nfs-server.service", state="active"} == 0
    for: 30s
  - alert: rhfs45.prolo_rootssh.path_NotActive
    annotations:
      description: ssh rhfs45.prolo journalctl -eu rootssh.path
      summary: rootssh.path is not active on rhfs45.prolo
    expr: node_systemd_unit_state{instance="rhfs45.prolo", name="rootssh.path", state="active"} == 0
    for: 30s
  - alert: rhfs67.prolo_udbsync_passwd.service_NotActive
    annotations:
      description: ssh rhfs67.prolo journalctl -eu udbsync_passwd.service
      summary: udbsync_passwd.service is not active on rhfs67.prolo
    expr: node_systemd_unit_state{instance="rhfs67.prolo", name="udbsync_passwd.service", state="active"} == 0
    for: 30s
  - alert: rhfs67.prolo_udbsync_passwd_nfsroot.service_NotActive
    annotations:
      description: ssh rhfs67.prolo journalctl -eu udbsync_passwd_nfsroot.service
      summary: udbsync_passwd_nfsroot.service is not active on rhfs67.prolo
    expr: node_systemd_unit_state{instance="rhfs67.prolo", name="udbsync_passwd_nfsroot.service", state="active"} == 0
    for: 30s
  - alert: rhfs67.prolo_udbsync_rootssh.service_NotActive
    annotations:
      description: ssh rhfs67.prolo journalctl -eu udbsync_rootssh.service
      summary: udbsync_rootssh.service is not active on rhfs67.prolo
    expr: node_systemd_unit_state{instance="rhfs67.prolo", name="udbsync_rootssh.service", state="active"} == 0
    for: 30s
  - alert: rhfs67.prolo_rpcbind.service_NotActive
    annotations:
      description: ssh rhfs67.prolo journalctl -eu rpcbind.service
      summary: rpcbind.service is not active on rhfs67.prolo
    expr: node_systemd_unit_state{instance="rhfs67.prolo", name="rpcbind.service", state="active"} == 0
    for: 30s
  - alert: rhfs67.prolo_nfs-server.service_NotActive
    annotations:
      description: ssh rhfs67.prolo journalctl -eu nfs-server.service
      summary: nfs-server.service is not active on rhfs67.prolo
    expr: node_systemd_unit_state{instance="rhfs67.prolo", name="nfs-server.service", state="active"} == 0
    for: 30s
  - alert: rhfs67.prolo_rootssh.path_NotActive
    annotations:
      description: ssh rhfs67.prolo journalctl -eu rootssh.path
      summary: rootssh.path is not active on rhfs67.prolo
    expr: node_systemd_unit_state{instance="rhfs67.prolo", name="rootssh.path", state="active"} == 0
    for: 30s
  - alert: rhfs89.prolo_udbsync_passwd.service_NotActive
    annotations:
      description: ssh rhfs89.prolo journalctl -eu udbsync_passwd.service
      summary: udbsync_passwd.service is not active on rhfs89.prolo
    expr: node_systemd_unit_state{instance="rhfs89.prolo", name="udbsync_passwd.service", state="active"} == 0
    for: 30s
  - alert: rhfs89.prolo_udbsync_passwd_nfsroot.service_NotActive
    annotations:
      description: ssh rhfs89.prolo journalctl -eu udbsync_passwd_nfsroot.service
      summary: udbsync_passwd_nfsroot.service is not active on rhfs89.prolo
    expr: node_systemd_unit_state{instance="rhfs89.prolo", name="udbsync_passwd_nfsroot.service", state="active"} == 0
    for: 30s
  - alert: rhfs89.prolo_udbsync_rootssh.service_NotActive
    annotations:
      description: ssh rhfs89.prolo journalctl -eu udbsync_rootssh.service
      summary: udbsync_rootssh.service is not active on rhfs89.prolo
    expr: node_systemd_unit_state{instance="rhfs89.prolo", name="udbsync_rootssh.service", state="active"} == 0
    for: 30s
  - alert: rhfs89.prolo_rpcbind.service_NotActive
    annotations:
      description: ssh rhfs89.prolo journalctl -eu rpcbind.service
      summary: rpcbind.service is not active on rhfs89.prolo
    expr: node_systemd_unit_state{instance="rhfs89.prolo", name="rpcbind.service", state="active"} == 0
    for: 30s
  - alert: rhfs89.prolo_nfs-server.service_NotActive
    annotations:
      description: ssh rhfs89.prolo journalctl -eu nfs-server.service
      summary: nfs-server.service is not active on rhfs89.prolo
    expr: node_systemd_unit_state{instance="rhfs89.prolo", name="nfs-server.service", state="active"} == 0
    for: 30s
  - alert: rhfs89.prolo_rootssh.path_NotActive
    annotations:
      description: ssh rhfs89.prolo journalctl -eu rootssh.path
      summary: rootssh.path is not active on rhfs89.prolo
    expr: node_systemd_unit_state{instance="rhfs89.prolo", name="rootssh.path", state="active"} == 0
    for: 30s
