- name: restart elasticsearch
  systemd:
    name: elasticsearch
    state: restarted
    daemon_reload: True

- name: restart kibana
  systemd:
    name: kibana
    state: restarted
    daemon_reload: True
