groups:
- name: alert.rules
  rules:
  - alert: CPUBusy
    expr: node_load5 > 2
    for: 10m
    annotations:
      description: The CPU load has been >2 for more than 10 minutes.
      summary: High CPU load
  - alert: MemoryActivity
    expr: deriv(node_memory_MemAvailable_bytes[3m]) > 1e+06
    for: 5m
    annotations:
      description: There has been a lot of activity on memory availability.
      summary: High memory activity
  - alert: FilesystemActivity
    expr: deriv(node_filesystem_free_bytes{device!="rootfs"}[3m]) > 1e+06
    for: 5m
    annotations:
      description: There has been a lot of activity on the filesystem.
      summary: High filesystem activity
  - alert: DiskSpaceLow
    expr: node_filesystem_free_bytes{fstype!="rootfs",mountpoint="/"} < 10e+09
    for: 5m
    annotations:
      description: A filesystem is running low on free space.
      summary: Low disk space
  - alert: TmpDiskSpaceLow
    expr: node_filesystem_free_bytes{mountpoint="/tmp"} < 5e+08
    for: 5m
    annotations:
      description: A filesystem is running low on free space.
      summary: Low /tmp space
  - alert: RAID1Degraded
    expr: node_md_disks_active < 2
    for: 1m
    annotations:
      description: 'The RAID1 array is degraded: at least one of the two disks is
        not active.'
      summary: RAID1 is degraded
  - alert: UnitFailed
    expr: node_systemd_unit_state{state="failed"} == 1
    for: 1m
    annotations:
      description: A systemd unit has failed.
      summary: Systemd unit failed
  - alert: SystemNotOperational
    expr: node_systemd_system_running == 0
    for: 1m
    annotations:
      description: See 'systemctl is-system-running'
      summary: A system is not operational
  - alert: LowMemory
    expr: node_memory_MemAvailable_bytes < 1e+09
    for: 5m
    annotations:
      description: The system has very low memory left.
      summary: Very low available memory

