- name: Create skeleton directory
  file:
    path: /export/skeleton
    state: directory
    mode: 0755

- name: Create skeleton directories
  file:
    path: "/export/skeleton/{{ item.path }}"
    state: directory
    mode: 0755
  with_filetree: skeleton/
  when: item.state == 'directory'
  loop_control:
    label: "{{ item.path }}"

- name: Install skeleton dotfiles
  copy:
    src: '{{ item.src }}'
    dest: "/export/skeleton/{{ item.path }}"
    mode: 0644
  with_filetree: skeleton/
  when: item.state == 'file'
  loop_control:
    label: "{{ item.path }}"

- name: Install the game of the year if contest has started
  pacman:
    name: 'prologin/{{ concours_game }}'
    state: "{{ 'present' if contest_started else 'absent' }}"
  tags: contest_mode

- name: Ensure player environment is absent when contest has not started
  file:
    path: '/export/skeleton/player'
    state: absent
  when: 'not contest_enabled'
  tags: contest_mode

- name: Install player environment in skeleton if contest has started
  command:
    cmd: 'stechec2-generator player --symlink {{ concours_game }} /export/skeleton/player'
    creates: '/export/skeleton/player'
  when: 'contest_enabled'
  tags: contest_mode
