- name: restart sshd
  systemd:
    name: sshd
    state: restarted
    daemon_reload: True

- name: restart timesyncd
  systemd:
    name: systemd-timesyncd
    state: restarted
    daemon_reload: True

- name: restart systemd-networkd
  systemd:
    name: systemd-networkd
    state: restarted
    daemon_reload: True
