- name: restart networkd
  systemd:
    name: systemd-networkd
    state: restarted
    daemon_reload: True

- name: restart resolved
  systemd:
    name: systemd-resolved
    state: restarted
    daemon_reload: True

- name: restart sysctl
  systemd:
    name: systemd-sysctl
    state: restarted
    daemon_reload: True
