- name: Install mdbdhcp systemd service
  template:
    src: 'systemd/mdbdhcp.service'
    dest: '/etc/systemd/system/mdbdhcp.service'
  notify: restart mdbdhcp

- name: Enable mdbdhcp
  systemd:
    name: mdbdhcp
    enabled: True
    state: started
