- name: Install prometheus
  pacman:
    name: prometheus

- name: Install prometheus systemd service
  template:
    src: 'systemd/prometheus.service'
    dest: '/etc/systemd/system/'
    mode: 0644
  notify: restart prometheus

- name: Install Prometheus nginx service
  template:
    src: 'nginx/prometheus.nginx'
    dest: '/etc/nginx/services'
    mode: 0644
  notify: reload nginx

- name: Install Prometheus configuration
  template:
    src: 'prometheus/{{ item }}'
    dest: '/etc/prometheus/'
    owner: prometheus
    group: prometheus
    mode: 0644
  loop:
    - prometheus.yml
    - alert.rules.yml
    - sadm.rules.yml
  notify: restart prometheus

- name: Enable prometheus
  systemd:
    name: prometheus
    enabled: True
    state: started
