- name: Install prometheus
  pacman:
    name: prometheus

- name: Install prometheus systemd service
  template:
    src: 'systemd/prometheus.service'
    dest: '/etc/systemd/system/'
    mode: 0644
  notify: restart prometheus

- name: Install Prometheus nginx service
  template:
    src: 'nginx/prometheus.nginx'
    dest: '/etc/nginx/services'
    mode: 0644
  notify: reload nginx

- name: Install Prometheus configuration
  template:
    src: 'prometheus/{{ item }}'
    dest: '/etc/prometheus/'
    owner: prometheus
    group: prometheus
    mode: 0644
  loop:
    - prometheus.yml
    - alert.rules.yml
    - sadm.rules.yml
  notify: restart prometheus

- name: Enable prometheus
  systemd:
    name: prometheus
    enabled: True
    state: started

# Flush the handlers to check that prometheus works
- meta: flush_handlers

- name: Wait for prometheus to become available
  wait_for:
    port: 9090

- name: Check that prometheus can be queried
  uri:
    url: http://localhost:9090/metrics
    return_content: yes
  register: prometheus_metrics
  tags: checks

- name: Check that prometheus returns metrics
  fail:
    msg: 'Prometheus content check failed at http://localhost:9090/metrics'
  when: "'prometheus_engine_queries' not in prometheus_metrics.content"
  tags: checks
