- name: Install nginx and dependencies
  pacman:
    name:
      - nginx
      - python-passlib
  notify: restart nginx

- name: Create nginx config directories
  file:
    path: "/etc/nginx/{{ item.path }}"
    state: directory
  with_filetree: nginx/
  when: item.state == 'directory'
  loop_control:
    label: "{{ item.path }}"

- name: Install nginx config files
  template:
    src: '{{ item.src }}'
    dest: "/etc/nginx/{{ item.path }}"
    mode: 0644
    lstrip_blocks: true
  with_filetree: nginx/
  when: item.state == 'file'
  loop_control:
    label: "{{ item.path }}"
  notify: reload nginx
  tags: contest_mode

- name: Create nginx service directory
  file:
    path: "/etc/nginx/services"
    state: directory

- name: Create nginx log directory
  file:
    path: "/var/log/nginx"
    state: directory
    mode: 0750
    owner: http
    group: log

- name: Symlink nginx log directory
  file:
    path: "/etc/nginx/logs"
    state: link
    src: "/var/log/nginx"

- name: Add nginx orga htpasswd file
  htpasswd:
    path: /etc/nginx/htpasswd_orga
    name: prologin
    password: '{{ nginx_orga_htpasswd }}'
    owner: root
    group: http
    mode: 0640

- name: Enable nginx
  systemd:
    name: nginx
    enabled: true
    state: started
    daemon_reload: true
