- name: Install conntrack-tools
  pacman:
    name: conntrack-tools

- name: Install conntrack systemd service
  template:
    src: 'systemd/conntrack.service'
    dest: '/etc/systemd/system/conntrack.service'
    mode: 0644
  notify: restart conntrack

- name: Enable conntrack
  systemd:
    name: conntrack
    enabled: True
    state: started
