- name: install the gw machine
  hosts:
    - gw
  remote_user: root
  roles:
    - {role: base, tags: base}
    - {role: gw_host_bootstrap, tags: gw_host_bootstrap}
    - {role: bind, tags: bind}
    - {role: dhcpd, tags: dhcpd}
    - {role: nginx, tags: nginx}
    - {role: postgresql, tags: postgresql}
    - {role: libprologin, tags: libprologin}
    - {role: mdb, tags: mdb}
    - {role: mdbsync, tags: mdbsync}
    - {role: mdbdns, tags: mdbdns}
    - {role: mdbdhcp, tags: mdbdhcp}
    - {role: netboot, tags: netboot}
    - {role: udb, tags: udb}
    - {role: udbsync, tags: udbsync}
    - role: udbsync_django
      tags: udbsync_django
      vars:
        udbsync_django_sites: [udb, mdb]
    - {role: udbsync_rootssh, tags: udbsync_rootssh}
    - {role: presencesync, tags: presencesync}
    - {role: presencesync_sso, tags: presencesync_sso}
