- name: install the rhfs machines
  hosts:
    - rhfs
  remote_user: root
  tasks:
    - name: Register RHFS machine in MDB
      mdb:
        hostname: 'rhfs{{ item.id }}'
        aliases: '{{ item.aliases|default([]) +
                  ["rfs" + (item.id|string), "hfs" + (item.id|string)] }}'
        mac: '{{ item.mac }}'
        mtype: service
        room: pasteur
      loop: '{{ rhfs_network }}'
      delegate_to: gw
      tags: mdb_register

    - import_role:
        name: networkd
      vars:
        network_config:
          - 10-rhfs-a.link
          - 10-rhfs-b.link
          - 10-rhfs.network
      tags: networkd

    - import_role:
        name: base
      tags: base

    - import_role:
        name: libprologin
      tags: libprologin

    - import_role:
        name: udbsync_rootssh
      tags: udbsync_rootssh

    - import_role:
        name: rfs
      tags: rfs

    - import_role:
        name: udbsync_rfs
      tags: udbsync_rfs

    - name: Install RFS export content
      when: rhfs_master
      delegate_to: rfs_staging
      tags: rfs_export
      block:
        - import_role:
            name: base
          tags: rfs_export_base

        - import_role:
            name: rfs_export_setup
          tags: rfs_export_setup

        - import_role:
            name: rfs_packages
          tags: rfs_export_packages
