- name: Create resource limit directories
  file:
    path: "/etc/systemd/system/{{ item.path }}"
    state: directory
    mode: 0755
  with_filetree: system/
  when: item.state == 'directory'
  loop_control:
    label: "{{ item.path }}"

- name: Install resource limit files
  copy:
    src: '{{ item.src }}'
    dest: "/etc/systemd/system/{{ item.path }}"
    mode: 0644
  with_filetree: system/
  when: item.state == 'file'
  loop_control:
    label: "{{ item.path }}"

- name: Install memory sysctl
  copy:
    src: 'sysctl/memory.conf'
    dest: '/etc/sysctl.d/'
    mode: 0644
